### PR TITLE
Fix bug in deviceprofile synchronization process

### LINKED ISSUE #18: [BUG] Errors in synchronization process of deviceprofile between cloud and edge
**What happened**:
- **Problem one:** After deleting the deviceprofile through edgex-core-metadata, the corresponding deviceprofile on openyurt will not be deleted;
- **Problem two:** With the restart of yurt-device-controller, openyurt may have a deviceprofile with two nodepool prefixes in its name.

**What you expected to happen**:
1. After deleting the deviceprofile through edgex-core-metadata, the corresponding deviceprofile on openyurt will be deleted;
2. During the synchronization process, no deviceprofiles whose names contain the two nodepool prefixes will appear.

**How to reproduce it (as minimally and precisely as possible)**:
- **Problem one：**
  1. Delete a deviceprofile object via edgex-core-metadata as follows：
    `curl -X 'DELETE' 'http://edgex-core-metadata:30081/api/v1/deviceprofile/name/[device profile name]' -H 'accept: */*'`
- **Problem two：**
  1. The operating environment is normal, and the cloud-edge resources are consistent;
  2. Delete a deviceprofile object via edgex-core-metadata; 
  3. Restart yurt-device-controller, then openyurt will have a deviceprofile with two nodepool prefixes in its name.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

### PR DESCRIPTION
**Pull request by qclc**
/bug
#### What this PR does / why we need it:
Fix bugs and solve the following problems：
- **Problem one:** After deleting the deviceprofile through edgex-core-metadata, the corresponding deviceprofile on openyurt will not be deleted;
- **Problem two:** With the restart of yurt-device-controller, openyurt may have a deviceprofile with two nodepool prefixes in its name.
#### Which issue(s) this PR fixes:

Fixes #18 

#### Special notes for your reviewer:

/assign @wawlian 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: api/v1alpha1/deviceprofile_types.go [hunk 1]
```diff
@@ -20,6 +20,10 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+const (
+	DeviceProfileFinalizer = "v1alpha1.deviceProfile.finalizer"
```
Comment (wawlian) [inline api/v1alpha1/deviceprofile_types.go:24]: Changing finalizer is a break change, we should add some logic for compatibility purpose when deleting device profile.
